Add (README.md): Add instructions for setting up systemd service
RangerMauve/hyper-gateway pull request #13
Opened 2023-03-19 15:48 UTC by josephmturner

From Adam's work [here](https://todo.sr.ht/~ushin/ushin/13#event-229700).

2023-03-19 15:54 UTC, josephmturner commented
Resolves #7.

2023-03-20 18:19 UTC, RangerMauve requested changes
Good start, I think without the info on the binary it might confuse folks though.

2023-03-20 18:19 UTC, RangerMauve commented on README.md
> +ExecStart=%h/.local/bin/hyper-gateway --writable true --silent true run
Would it be possible to have more docs added to this to explain how to get `hyper-gateway` into that location? Or what to do if you don't already have it there.

2023-03-20 18:19 UTC, RangerMauve commented on README.md
> +### How to run hyper-gateway as a background process?
```suggestion
### How can I run hyper-gateway as a background process? (On Linux)
```

2023-03-20 19:06 UTC, josephmturner commented on README.md
> +ExecStart=%h/.local/bin/hyper-gateway --writable true --silent true run
Please check latest commit :)

2023-03-21 17:42 UTC, RangerMauve approved these changes
This is perfect, thank you!

2023-03-21 17:43 UTC, merged